using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Netrin.Antifraude.Infrastructure.Data.Migrations
{
    public partial class mig002 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM "Transacoes")
                        OR EXISTS (SELECT 1 FROM "StatusTransacoes")
                        OR EXISTS (SELECT 1 FROM "Avaliacoes") THEN
                        RAISE EXCEPTION 'mig-002 requer as tabelas de transações vazias.';
                    END IF;
                END $$;
                """);

            migrationBuilder.DropTable("Avaliacoes");
            migrationBuilder.DropTable("StatusTransacoes");
            migrationBuilder.DropTable("Transacoes");

            migrationBuilder.Sql("""
                CREATE TABLE "Transacoes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "IdempotencyKey" character varying(100) NOT NULL,
                    "Valor" numeric NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL
                );
                CREATE UNIQUE INDEX "IX_Transacoes_IdempotencyKey" ON "Transacoes" ("IdempotencyKey");

                CREATE TABLE "StatusTransacoes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Status" text NOT NULL,
                    "TransacaoId" integer NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL,
                    CONSTRAINT "FK_StatusTransacoes_Transacoes_TransacaoId"
                        FOREIGN KEY ("TransacaoId") REFERENCES "Transacoes" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX "IX_StatusTransacoes_TransacaoId" ON "StatusTransacoes" ("TransacaoId");

                CREATE TABLE "Avaliacoes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Decisao" character varying(30) NOT NULL,
                    "Motivo" text NULL,
                    "TransacaoId" integer NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL,
                    CONSTRAINT "FK_Avaliacoes_Transacoes_TransacaoId"
                        FOREIGN KEY ("TransacaoId") REFERENCES "Transacoes" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX "IX_Avaliacoes_TransacaoId" ON "Avaliacoes" ("TransacaoId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM "Transacoes")
                        OR EXISTS (SELECT 1 FROM "StatusTransacoes")
                        OR EXISTS (SELECT 1 FROM "Avaliacoes") THEN
                        RAISE EXCEPTION 'Reverter mig-002 requer as tabelas de transações vazias.';
                    END IF;
                END $$;
                """);

            migrationBuilder.DropTable("Avaliacoes");
            migrationBuilder.DropTable("StatusTransacoes");
            migrationBuilder.DropTable("Transacoes");

            migrationBuilder.Sql("""
                CREATE TABLE "Transacoes" (
                    "Id" uuid PRIMARY KEY,
                    "IdempotencyKey" character varying(100) NOT NULL,
                    "Valor" numeric NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL
                );
                CREATE UNIQUE INDEX "IX_Transacoes_IdempotencyKey" ON "Transacoes" ("IdempotencyKey");

                CREATE TABLE "StatusTransacoes" (
                    "Id" uuid PRIMARY KEY,
                    "Status" text NOT NULL,
                    "TransacaoId" uuid NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL,
                    CONSTRAINT "FK_StatusTransacoes_Transacoes_TransacaoId"
                        FOREIGN KEY ("TransacaoId") REFERENCES "Transacoes" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX "IX_StatusTransacoes_TransacaoId" ON "StatusTransacoes" ("TransacaoId");

                CREATE TABLE "Avaliacoes" (
                    "Id" uuid PRIMARY KEY,
                    "Decisao" character varying(30) NOT NULL,
                    "Motivo" text NULL,
                    "TransacaoId" uuid NOT NULL,
                    "DataCriacao" timestamp with time zone NOT NULL,
                    "DataAtualizacao" timestamp with time zone NULL,
                    "EhAtivo" boolean NOT NULL,
                    CONSTRAINT "FK_Avaliacoes_Transacoes_TransacaoId"
                        FOREIGN KEY ("TransacaoId") REFERENCES "Transacoes" ("Id") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX "IX_Avaliacoes_TransacaoId" ON "Avaliacoes" ("TransacaoId");
                """);
        }
    }
}
